config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :follows
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
    belongs_to :followee, foreign_key: :followee_id, class_name: 'User'

end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    has_one_attached :image

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

         has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
         has_many :followees, through: :followed_users
        
         has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
         has_many :followers, through: :following_users
       
         

         def follow(user)
           followed_users.create(followee_id: user.id)
         end
       
         def unfollow(user)
           followed_users.find_by(followee_id: user.id).delete
         end

         has_many :posts
          
         has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?


    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name, :username,:mobile_number,:gender,:date_of_birth])
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_user

    def index
        @follows = Follow.all
    end

    def create
        current_user.follow(@user)
        redirect_to @user
    end
  
    def destroy
        current_user.unfollow(@user)
        redirect_to @user
    end
  
    private
  
    def find_user
        @user = User.find(params[:user_id])
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!
   def index
    if current_user
      @posts = Post.order(created_at: :desc)
    else
      redirect_to new_user_session_path
    end
    
   end

  
  def create

      @post = Post.new(post_params)
    
      if @post.save
        redirect_to @post
      else
        render :new, status: :unprocessable_entity
        flash[:notice] = "post has been created."
      end

    end

    def show
        @post = Post.find(params[:id])
    end
      
    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy
  
      redirect_to user_path(current_user)
    end
    
    def new
      @post = Post.new
    end


    private
      def post_params
        params.require(:post).permit(:description, :image, :user_id)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    

    def show
        @user = User.find(params[:id])
        @posts = @user.posts.order(created_at: :desc)
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "user has been created succesfully"
            redirect_to root_path
        else
          render :new, status: :unprocessable_entity
          flash[:alert] = "user not created,Try again"
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to root_path
            flash[:success] = "user has been updated succesfully"
        else
          render :edit, status: :unprocessable_entity
          flash[:alert] = "user not updated,Try again"
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path, status: :see_other
        flash[:success] = "User has been destroyed succesfully"
    end
    

    private
    def user_params
        params.require(:user).permit(:first_name,:last_name,:gender,:username,:date_of_birth,:mobile_number,:email,:password,:password_confirmation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/index.html.erb
<h1>LIST OF USERS </h1>

<table>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Mobile_number</th>
    </tr>
<% User.all.each do |user| %>
    <tr>
     <td>
     <%= link_to user.username,user%>
     </td>
     <td>
     <%= user.email%>
     </td>
     <td>
     <%= user.mobile_number%>
     </td>
    </tr>
    <% end %>
</table>

<%= link_to "ADD NEW USER", new_user_path %>

app/views/home/index.html.erb
<h1 class="mt-5">Welcome to Postgrams</h1>

<p class="lead">Please register or sign in to continue.</p>

<%= link_to "Sign up", new_user_path, class:  "btn btn-success" %>

<%= link_to "Sign in", new_user_session_path, class:  "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskfour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1> What do you want to talk about?  </h1>
    <%= form_for Post.new do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :description %></br>
        </div>
        
        <div class="form-group">
        <%= f.file_field :image %>
        </div>
        
        <div class="form-group">
          <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
        </div>
        <br>
        <div class="text-center">
          <%= f.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>

app/views/posts/_post.html.erb
<section class="post">
<div class="user">
  <div class="avatar">
    <img src="user_avatar.jpg">
  </div>
  <div class="username">
    <%= post.user.username %>
  </div>
</div>
<%= image_tag post.image, class: 'main-image' %>
<div class="description">
  <%= post.description %>
</div>
</section>

app/views/posts/index.html.erb
<div class="homepage">
  <div class='form-upload'>
    <%= render 'form' %>
  </div>

<div class="posts">
<% @posts.each do |post| %>
  <%= render partial: 'post', locals: { post: post } %>
<% end %>

</div>
</div>

app/views/posts/new.html.erb
<h1> create a new post </h1>
<%= render "form" %>

app/views/users/_follow_button.html.erb
<%= button_to "unfollow", follow_path(user_id: @user.id), method: :delete, class:"btn-btn-danger"%>

<%= button_to "follow", follows_path(user_id: @user.id), method: :post %>

app/views/users/_follower_count.html.erb
<div>
<%= pluralize(user.followers.count, "follower")%>
</div>

app/views/users/_form.html.erb
<div class="form">
<%= form_with model: @user do |form|  %>
    <div>
      <%= form.label :first_name %><br>
      <%= form.text_field :first_name %><br>
      <% @user.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  

    <div>
      <%= form.label :last_name %><br>
      <%= form.text_field :last_name %><br>
      <% @user.errors.full_messages_for(:last_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %><br>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>

    <div>
    <%= form.label :mobile_number %><br>
    <%= form.text_field :mobile_number %><br>
    <% @user.errors.full_messages_for(:mobile_number).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>

    <div>
    <%= form.label :gender %><br>
    <%= form.select :gender, ['Male', 'Female'] %></br>
    <% @user.errors.full_messages_for(:gender).each do |message| %>
        <div><%= message %></div>
    <% end %>
    </div>

    <div>
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :date_of_birth %></br>
    <% @user.errors.full_messages_for(:date_of_birth).each do |message| %>
        <div><%= message %></div>
    <% end %>
    </div>

    <div class="field">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= form.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>


  <div class="actions">
  <%= form.submit "Sign up" %>
</div>
<% end %>
    
  
  </div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1> CREATE A NEW USER </h1>
<%= render "form" %>

app/views/users/show.html.erb
<%= @user.email %>

<%= render 'users/follower_count', user: @user%>
<div><%= @user.followees.count %> following</div>


<%= render 'users/follow_button', user: @user %>